# Generated by Django 5.0.4 on 2024-04-30 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0002_rename_field_id_user_field_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFieldsChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgbot.field')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgbot.user_tg')),
            ],
        ),
    ]
