# Generated by Django 5.0.4 on 2024-04-30 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0003_userfieldschange'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfieldschange',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
