# Generated by Django 4.2.13 on 2024-05-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0005_remove_userfieldschange_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_doc',
            name='PDF',
            field=models.FileField(default=1, upload_to='documents/'),
            preserve_default=False,
        ),
    ]
